Final Milestone
ccobasi/todo2.1 pull request #5
Opened 2021-07-23 07:37 UTC by ccobasi

- Implement add task function
- Implement delete task function
- Implement clear all function

2021-07-23 08:52 UTC, Davidosky007 requested changes
# Hi @ccobasi 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
* Kindly check below and make the necessary changes to the List `array` in the local storage, it should be able to hold more tasks. 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-23 08:52 UTC, Davidosky007 commented on src/addRemove.js
> +}
* Currently only one task can be added in the `list` array,  so as a result other features[[These features](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m3_add_remove.md#:~:text=By%20default%20new,in%20local%20storage.)] of this milestone cant be tested kindly fix this 🙏

2021-07-23 22:34 UTC, MahmoudBakr23 approved these changes
Hi @ccobasi 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-24 20:00 UTC, ccobasi commented
Have not merged PR

2021-07-24 20:00 UTC, merged